id: ID24E54FD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:03:45+00:00'
last_modified: '2022-06-08T16:12:21.833030+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8046
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་གྱི་གསུང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    86C8:
      image_group_id: I3CN8409
      title: ''
      total_pages: 284
      order: 1
      base_file: 86C8.txt
    66F9:
      image_group_id: I3CN8410
      title: ''
      total_pages: 378
      order: 2
      base_file: 66F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
