id: P010607
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN8046
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་གྱི་གསུང་རྣམ།
  author: ''
  volumes:
    9b2be8755cbe4a57b3870b1b148ce65c:
      image_group_id: I3CN8409
      title: ''
      volume_number: 1
      total_pages: 284
      base_file: v001.txt
    f12c1a207c024271bb67197933b044c8:
      image_group_id: I3CN8410
      title: ''
      volume_number: 2
      total_pages: 378
      base_file: v002.txt
